version: "3.2"

services:

  php:
    container_name: php
    build: 
      context: './dockerBuilds/php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/

  apache:
    container_name: apache
    build:
      context: './dockerBuilds/apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_ROOT-../public_html}/:/var/www/html/
    
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - mysql
    ports:
      - '8080:80'
    networks:
      - backend
    environment:
      PMA_HOST: mysql
    volumes: 
      - /sessions

networks:
  frontend:
  backend:
volumes:
    data: